name: ZAP Scan (PR)
run-name: ${{ github.actor }} is performing a DAST scan using ZAP 🚀

# Trigger this workflow when a pull request is opened or updated with new commits
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]  # opened = new PR; synchronize = push to existing PR
        
jobs:
  zap_scan:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create a place holder report file. Replace this with your actual scan output.
      - name: Create a sample file
        run: echo "This is a test file." > security_report.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ZAP Security Scan
        run: python3 basic-scan.py
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
          ZAP_PATH: ${{ secrets.ZAP_PATH }}
          ZAP_PORT: 8080
          TARGET_URL: http://localhost:3000/
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ZAP_HOST: http://localhost

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security_report.txt

      # Post a comment on the PR with a link to the artifact
      - name: Comment on the PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this token automatically for the workflow
          issue-number: ${{ github.event.pull_request.number }}  # Gets the current PR number dynamically
          body: |
            👋 Hello! Here's the security scan report.

            ✅ You can [download the full report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) from the "Artifacts" section of this workflow run.

            📄 This helps reviewers quickly access the scan results and take action if needed.
