name: ZAP Scan (Push)
run-name: ${{ github.actor }} is performing a DAST scan using ZAP 🚀
# on: [push]
        
jobs:
  zap_scan:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ZAP Security Scan
        run: python3 basic-scan.py
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
          ZAP_PATH: ${{ secrets.ZAP_PATH }}
          ZAP_PORT: 8080
          TARGET_URL: http://localhost:3000/
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ZAP_HOST: http://localhost
